spring:
  config:
    activate:
      on-profile: s3
cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
      dir: ${AWS_S3_DIR}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false